import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    backgroundColor: '#de0000',
    paddingVertical: 2,
    paddingHorizontal: 16,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoContainer: {
    flex: 1,
  },
  headerLogo: {
    width: 120,
    height: 32,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconButton: {
    padding: 4,
  },
  profileButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  mainContent: {
    flex: 1,
    backgroundColor: '#700A06',
  },
  statusContainer: {
    padding: 16,
    paddingBottom: 100,
  },
  statusCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
    justifyContent: 'center',
  },
  statusLabel: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  statusValue: {
    fontSize: 16,
    color: '#ffcf00',
    fontWeight: 'bold',
  },
  stepsGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  timelineStep: {
    alignItems: 'center',
    flex: 1,
    position: 'relative',
  },
  timelineLine: {
    position: 'absolute',
    top: 25,
    left: '60%',
    width: '80%',
    height: 2,
    backgroundColor: '#f0f0f0',
    zIndex: 0,
  },
  stepsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 30,
  },
  stepContainer: {
    alignItems: 'center',
    flex: 1,
    zIndex: 1,
    backgroundColor: 'transparent',
  },
  stepCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#333',
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    position: 'relative',
    zIndex: 2,
  },
  completedCircle: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  activeCircle: {
    borderColor: '#de0000',
    backgroundColor: '#de0000',
  },
  pendingCircle: {
    borderColor: '#ccc',
    backgroundColor: 'white',
  },
  stepNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#999',
  },
  stepNumberActive: {
    color: 'white',
  },
  stepNumberPending: {
    color: '#999',
  },
  stepTitle: {
    fontSize: 9,
    color: '#666',
    textAlign: 'center',
    fontWeight: '400',
    marginTop: 4,
    maxWidth: 80,
  },
  stepTitleActive: {
    color: '#de0000',
    fontWeight: '600',
  },
  emptyStep: {
    flex: 1,
  },
  actionButton: {
    backgroundColor: '#de0000',
    borderRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignSelf: 'center',
    marginBottom: 20,
  },
  actionButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  contactSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  contactTitle: {
    fontSize: 18,
    color: '#333',
    marginBottom: 4,
  },
  contactNumber: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
    marginBottom: 2,
  },
  contactEmail: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  paymentButtonSection: {
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  goToPaymentButton: {
    backgroundColor: '#4CAF50',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    gap: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  goToPaymentButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  paymentButtonHint: {
    fontSize: 12,
    color: '#666',
    marginTop: 8,
    textAlign: 'center',
  },
  uploadSection: {
    alignItems: 'center',
  },
  uploadTitle: {
    fontSize: 18,
    color: '#333',
    marginBottom: 8,
    fontWeight: '500',
  },
  uploadContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  uploadButton: {
    backgroundColor: '#de0000',
    borderRadius: 4,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  uploadButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
  },
  uploadText: {
    fontSize: 16,
    color: '#666',
    marginTop: 8,
  },
  uploadButtonDisabled: {
    backgroundColor: '#999',
    opacity: 0.6,
  },
  uploadSuccessText: {
    fontSize: 16,
    color: '#4CAF50',
    marginTop: 8,
    textAlign: 'center',
  },
  noDataContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  noDataTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 18,
    marginBottom: 8,
  },
  noDataText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  infoSection: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  enrolleeIdContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  copyButton: {
    padding: 4,
    backgroundColor: '#fee',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  infoLabel: {
    fontSize: 13,
    color: '#666',
    fontWeight: '500',
    minWidth: 90,
  },
  infoValue: {
    fontSize: 13,
    color: '#333',
    fontWeight: '600',
    flex: 1,
  },
  infoPriceValue: {
    fontSize: 13,
    color: '#de0000',
    fontWeight: '700',
    flex: 1,
    textDecorationLine: 'underline',
  },
  statusBadge: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: 'white',
  },
  statusBadgeCompleted: {
    backgroundColor: '#4CAF50',
  },
  statusBadgeApproved: {
    backgroundColor: '#2196F3',
  },
  statusBadgeVerified: {
    backgroundColor: '#FFC107',
  },
  statusBadgePaymentPending: {
    backgroundColor: '#FF9800',
  },
  statusBadgeRejected: {
    backgroundColor: '#F44336',
  },
  statusBadgePending: {
    backgroundColor: '#9E9E9E',
  },
  progressSection: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#de0000',
    marginBottom: 16,
  },
  remarksSection: {
    marginBottom: 20,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  remarksText: {
    fontSize: 18,
    color: '#666',
    lineHeight: 20,
  },
  adminRemarksSection: {
    borderRadius: 8,
    padding: 16,
    marginBottom: 20,
    borderLeftWidth: 4,
  },
  adminRemarksRejected: {
    backgroundColor: '#fef2f2',
    borderLeftColor: '#dc2626',
  },
  adminRemarksOther: {
    backgroundColor: '#eff6ff',
    borderLeftColor: '#2563eb',
  },
  adminRemarksHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  adminRemarksTitle: {
    fontSize: 14,
    fontWeight: '600',
  },
  adminRemarksTitleRejected: {
    color: '#991b1b',
  },
  adminRemarksTitleOther: {
    color: '#1e40af',
  },
  adminRemarksText: {
    fontSize: 14,
    lineHeight: 20,
  },
  adminRemarksTextRejected: {
    color: '#b91c1c',
  },
  adminRemarksTextOther: {
    color: '#1d4ed8',
  },
  noteSection: {
    backgroundColor: '#E3F2FD',
    borderRadius: 8,
    padding: 12,
    marginBottom: 20,
    marginTop: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#2196F3',
  },
  noteTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1976D2',
    marginBottom: 8,
  },
  noteText: {
    fontSize: 16,
    color: '#1565C0',
    marginBottom: 4,
  },
  studentIdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  studentIdValue: {
    fontSize: 16,
    color: '#1565C0',
    fontWeight: '700',
  },
  noteCopyButton: {
    padding: 6,
    backgroundColor: '#fee',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#de0000',
  },
  bottomNavigation: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'white',
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
  },
  navText: {
    fontSize: 16,
    color: '#666',
    marginTop: 4,
    textAlign: 'center',
  },
  activeNavText: {
    color: '#de0000',
    fontWeight: '500',
  },
});
