import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fffdf2",
  },
  header: {
    width: "100%",
    height: 57,
    backgroundColor: "#de0000",
    borderBottomWidth: 1,
    borderBottomColor: "#700a06",
    justifyContent: "center",
    alignItems: "center",
  },
  headerLogo: {
    width: 130,
    height: 38,
    marginTop: 8,
  },
  main: {
    flex: 1,
    alignItems: "center",
    marginTop: 50,
  },
  card: {
    width: 336,
    backgroundColor: "#700A06",
    borderRadius: 8,
    padding: 16,
    alignItems: "center",
  },
  welcomeText: {
    marginTop: 26,
    fontWeight: "bold",
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
  },
  logo: {
    width: 239,
    height: 60,
    marginTop: 8,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    width: "80%",
    height: 60,
    marginTop: 20,
    backgroundColor: "#fff",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#000",
    paddingHorizontal: 8,
  },
  inputIcon: {
    marginRight: 8,
  },
  input: {
    flex: 1,
    height: "100%",
    color: "#6d6d6d",
    fontSize: 24,
  },
  eyeButton: {
    padding: 4,
  },
  forgotWrapper: {
    width: "100%",
    alignItems: "flex-end",
    marginTop: 8,
    paddingRight: 24,
  },
  forgotText: {
    color: "#ffcf00",
    fontWeight: "bold",
    fontSize: 18,
    textDecorationLine: "underline",
  },
  loginButton: {
    width: "80%",
    marginTop: 20,
    backgroundColor: "#dd0000",
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
    padding: 10,
  },
  loginButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 24,
  },
  signupWrapper: {
    flexDirection: "row",
    marginTop: 16,
    alignItems: "center",
  },
  signupText: {
    color: "#fffdf2",
    fontSize: 10,
  },
  signupLink: {
    color: "#ffcf00",
    fontSize: 10,
    marginLeft: 4,
    textDecorationLine: "underline",
  },
  termsText: {
    marginTop: 30,
    color: "#fffdf2",
    fontSize: 18,
    textAlign: "center",
  },
  termsLink: {
    color: "#ffcf00",
    textDecorationLine: "underline",
  },
  enrollButtonWrapper: {
    marginTop: 20,
    width: "100%",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#fff",
    paddingTop: 10,
  },
  loginButtonWrapper: {
    width: "100%",
    alignItems: "center",
    marginBottom: 10,
  },
  enrollButtonText: {
    color: "#fffdf2",
    fontSize: 15,
  },
});
